---
abstract: 'Plack application for NKC MARC demo.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-NKC-MARC
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  Business::ISBN: 0
  Business::ISSN: 0
  Data::HTML::Element::A: 0
  Data::HTML::Element::Option: 0
  Data::HTML::Element::Select: 0.14
  Data::Message::Simple: 0
  Data::NKC::MARC::Menu: 0
  Error::Pure: 0
  File::Share: 0
  IO::File: 0
  List::Util: 1.33
  MARC::File::XML: 0
  MARC::Record: 0
  NKC::Transform::MARC2BIBFRAME: 0
  Plack::App::CPAN::Changes: 0
  Plack::App::Search: 0.05
  Plack::App::URLMap: 0
  Plack::Component: 0
  Plack::Request: 0
  Plack::Session: 0
  Plack::Util::Accessor: 0
  Readonly: 0
  Scalar::Util: 0
  Tags::HTML::Container: 0.07
  Tags::HTML::Element::Option: 0
  Tags::HTML::Element::Select: 0.12
  Tags::HTML::Messages: 0
  Tags::HTML::NKC::MARC::Menu: 0
  Tags::HTML::Table::View: 0.06
  Tags::HTML::XML::Raw: 0
  Tags::HTML::XML::Raw::Color: 0
  Text::CSV_XS: 0
  Unicode::UTF8: 0
  ZOOM: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/michal-josef-spacek/Plack-App-NKC-MARC/issues
  homepage: https://github.com/michal-josef-spacek/Plack-App-NKC-MARC
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Plack-App-NKC-MARC
version: '0.06'
